twig:
    default_path: '%kernel.project_dir%/templates'

when@test:
    twig:
        strict_variables: true

knp_paginator:
    template:
        pagination: '@KnpPaginator/Pagination/twitter_bootstrap_v4_pagination.html.twig'
        sortable: '@KnpPaginator/Pagination/twitter_bootstrap_v4_font_awesome_sortable_link.html.twig'

